APPLICATION=HelloWorld

BOARD ?= native
FEATURES_REQUIRED += periph_spi

RIOTBASE ?= $(CURDIR)/../../RIOT
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += periph_spi
USEMODULE += printf_float
USEMODULE += xtimer


DEVELHELP ?= 1

include $(RIOTBASE)/Makefile.include
